version: '3'
services:
  node:
    build:
      context: ./Node
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=people

  db:
    build:
      context: ./MySQL
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=people

  nginx:
    build:
      context: ./NGINX
    ports:
      - "8000:8000"
    depends_on:
      - node
